/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: user.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as user_pb from './user_pb'; // proto import: "user.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class LoginServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/auth.LoginService/Register',
    grpcWeb.MethodType.UNARY,
    user_pb.RegisterRequest,
    user_pb.AuthResponse,
    (request: user_pb.RegisterRequest) => {
      return request.serializeBinary();
    },
    user_pb.AuthResponse.deserializeBinary
  );

  register(
    request: user_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null): Promise<user_pb.AuthResponse>;

  register(
    request: user_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.AuthResponse) => void): grpcWeb.ClientReadableStream<user_pb.AuthResponse>;

  register(
    request: user_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.AuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.LoginService/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.LoginService/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/auth.LoginService/Login',
    grpcWeb.MethodType.UNARY,
    user_pb.LoginRequest,
    user_pb.AuthResponse,
    (request: user_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    user_pb.AuthResponse.deserializeBinary
  );

  login(
    request: user_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<user_pb.AuthResponse>;

  login(
    request: user_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.AuthResponse) => void): grpcWeb.ClientReadableStream<user_pb.AuthResponse>;

  login(
    request: user_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.AuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.LoginService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.LoginService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorListUsers = new grpcWeb.MethodDescriptor(
    '/auth.LoginService/ListUsers',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    user_pb.ListUsersResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    user_pb.ListUsersResponse.deserializeBinary
  );

  listUsers(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<user_pb.ListUsersResponse>;

  listUsers(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.ListUsersResponse) => void): grpcWeb.ClientReadableStream<user_pb.ListUsersResponse>;

  listUsers(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.ListUsersResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.LoginService/ListUsers',
        request,
        metadata || {},
        this.methodDescriptorListUsers,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.LoginService/ListUsers',
    request,
    metadata || {},
    this.methodDescriptorListUsers);
  }

}

